<a href="https://colab.research.google.com/github/nithinkt09/dlexp/blob/main/pyto_exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

import os
data_folder = '/content/drive/MyDrive/dataexp'

if os.path.exists(data_folder):
  print("Data folder exists")
else:
  print("Data folder does not exist")

Mounted at /content/drive/
Data folder exists


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


tensor: multidimensional array (a gneral form of a matrix) similar to that of numpy array that holds numerical data, where they can be scalar, vector, or multidemensional

In [ ]:
# scalar
scalar = torch.torch.tensor(32)
print(scalar)
print(f'tensor type: {type(scalar)}')
print(f'dimension: {scalar.ndim}')
print(f'value: {scalar.item()}')

tensor(32)
tensor type: <class 'torch.Tensor'>
dimension: 0
value: 32


In [ ]:
# vector
vector = torch.tensor([1, 2, 3])
print(vector)
print(f'tensor type: {type(vector)}')
print(f'dimension: {vector.ndim}')
print(f'shape: {vector.shape}')

tensor([1, 2, 3])
tensor type: <class 'torch.Tensor'>
dimension: 1
shape: torch.Size([3])


In [ ]:
# matrix
MATRIX = torch.tensor([[1, 3, 1], [4, 9, 5]])
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])
print(MATRIX[1][2])

2
torch.Size([2, 3])
tensor([4, 9, 5])
tensor(5)


In [ ]:
# tensor
TENSOR = torch.tensor(
   [
       [
        [[1, 2, 3],  [5, 1, 4], [9, 3, 2]],
        [[8, 92, 43], [5, 1, 4], [9, 3, 2]]
        ]
     ]
)
print(TENSOR.shape)

torch.Size([1, 2, 3, 3])


In [ ]:
# random tensor
random_tensor = torch.rand(1, 2, 2, 3)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[[[0.1419, 0.0295, 0.2107],
          [0.0501, 0.2930, 0.4810]],

         [[0.2610, 0.8212, 0.9816],
          [0.9523, 0.8546, 0.3446]]]])
4
torch.Size([1, 2, 2, 3])


In [ ]:
# zero tensors
ZERO_TENSOR = torch.zeros(2, 3,)

# one tensors
ONE_TENSOR = torch.ones(2, 2)

# identity tensor
IDENTITY_TENSOR = torch.eye(3)

print(ZERO_TENSOR)
print(ONE_TENSOR)
print(IDENTITY_TENSOR)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
A = torch.rand(10, 3)
B = torch.rand(3, 4)
C = torch.matmul(A, B)
print(C)
print(C.shape)

tensor([[0.4272, 1.3082, 0.6278, 0.9775],
        [0.5471, 1.5798, 0.7480, 1.2788],
        [0.1437, 0.4412, 0.1849, 0.3604],
        [0.5040, 1.3053, 0.7766, 1.0119],
        [0.1445, 0.4786, 0.2109, 0.3474],
        [0.4143, 1.3167, 0.5212, 1.0717],
        [0.1840, 0.7075, 0.2155, 0.5458],
        [0.3157, 0.9150, 0.4361, 0.7340],
        [0.4910, 1.7060, 0.6357, 1.3092],
        [0.3598, 1.5735, 0.3722, 1.2043]])
torch.Size([10, 4])


In [ ]:
x = torch.rand(10, dtype=torch.float32)
print(x.min())
print(x.max())
print(x.mean())
print(x.argmin())
print(x.argmax())


tensor(0.0431)
tensor(0.9149)
tensor(0.3365)
tensor(8)
tensor(6)


In [ ]:
# reshaping
x = torch.arange(1., 10)

x_reshaped = x.reshape(3, 3)
print(x_reshaped)
print(x.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.float32


In [ ]:
# stack tensors on top
